"""update_alert_log_schema

Revision ID: b3e331f88200
Revises: abd31e77dc8f
Create Date: 2026-01-27 01:24:10.662276+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3e331f88200'
down_revision: Union[str, None] = 'abd31e77dc8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Manually create Enum type for Postgres
    op.execute("DO $$ BEGIN CREATE TYPE alertlevel AS ENUM ('INFO', 'WARNING', 'CRITICAL'); EXCEPTION WHEN duplicate_object THEN null; END $$;")
    
    op.add_column('alert_logs', sa.Column('track_id', sa.String(length=64), nullable=True))
    op.add_column('alert_logs', sa.Column('alert_level', sa.Enum('INFO', 'WARNING', 'CRITICAL', name='alertlevel'), nullable=False, server_default=sa.text("'INFO'")))
    op.add_column('alert_logs', sa.Column('best_body_image_path', sa.String(length=500), nullable=True))
    op.add_column('alert_logs', sa.Column('image_history', sa.JSON(), nullable=True))
    op.add_column('alert_logs', sa.Column('is_reviewed', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('alert_logs', sa.Column('start_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('alert_logs', sa.Column('end_time', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_alert_logs_track_id'), 'alert_logs', ['track_id'], unique=False)
    op.drop_constraint(op.f('alert_logs_camera_id_fkey'), 'alert_logs', type_='foreignkey')
    op.create_foreign_key(None, 'alert_logs', 'cameras', ['camera_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'alert_logs', type_='foreignkey')
    op.create_foreign_key(op.f('alert_logs_camera_id_fkey'), 'alert_logs', 'cameras', ['camera_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_alert_logs_track_id'), table_name='alert_logs')
    op.drop_column('alert_logs', 'end_time')
    op.drop_column('alert_logs', 'start_time')
    op.drop_column('alert_logs', 'is_reviewed')
    op.drop_column('alert_logs', 'image_history')
    op.drop_column('alert_logs', 'best_body_image_path')
    op.drop_column('alert_logs', 'alert_level')
    op.drop_column('alert_logs', 'track_id')
    # ### end Alembic commands ###
