# Pydantic Schemas Package

from app.schemas.common import ResponseBase, ErrorResponse, PaginatedResponse
from app.schemas.auth import (
    LoginRequest,
    TokenResponse,
    RefreshTokenRequest,
    ChangePasswordRequest,
    UserResponse,
)
from app.schemas.user import (
    UserRoleEnum,
    UserBase,
    UserCreate,
    UserUpdate,
    UserStatusUpdate,
    ResetPasswordRequest,
    UserDetailResponse,
    UserListResponse,
)
from app.schemas.zone import (
    ZoneBase,
    ZoneCreate,
    ZoneUpdate,
    ZoneResponse,
    ZoneSimpleResponse,
    ZoneListResponse,
    ZoneTreeNode,
    ZoneTreeResponse,
)
from app.schemas.camera import (
    CameraStatusEnum,
    CameraBase,
    CameraCreate,
    CameraUpdate,
    CameraToggleRequest,
    CameraResponse,
    CameraSimpleResponse,
    CameraListResponse,
    CameraStatusResponse,
    CameraStatusListResponse,
    CameraTestResult,
)
from app.schemas.group import (
    GroupBase,
    GroupCreate,
    GroupUpdate,
    GroupResponse,
    GroupSimpleResponse,
    GroupListResponse,
    GroupStatsResponse,
)
from app.schemas.person import (
    PersonBase,
    PersonCreate,
    PersonUpdate,
    PersonStatusUpdate,
    PersonResponse,
    PersonDetailResponse,
    PersonSimpleResponse,
    PersonListResponse,
    FaceImageResponse,
    FaceUploadResponse,
    PersonImportRequest,
    PersonImportResult,
)
from app.schemas.alert import (
    AlertTypeEnum,
    AlertStatusEnum,
    AlertResponse,
    AlertListResponse,
    AlertProcessRequest,
    AlertIgnoreRequest,
    AlertBatchProcessRequest,
    AlertBatchProcessResult,
    AlertStatistics,
    AlertTrendItem,
    AlertTrendResponse,
    AlertCreateRequest,
)
from app.schemas.settings import (
    ConfigValueType,
    ConfigItemResponse,
    ConfigGroupResponse,
    SystemConfigResponse,
    ConfigUpdateItem,
    ConfigUpdateRequest,
    ConfigUpdateResult,
    CleanupTypeEnum,
    CleanupRequest,
    CleanupResult,
    CleanupLogResponse,
    CleanupLogListResponse,
    DiskUsage,
    ServiceStatus,
    DatabaseStatus,
    SystemStatusResponse,
)
from app.schemas.log import (
    ActionTypeEnum,
    TargetTypeEnum,
    OperationLogResponse,
    OperationLogListResponse,
    OperationLogCreateRequest,
    OperationLogStatistics,
    ACTION_LABELS,
    TARGET_TYPE_LABELS,
)

__all__ = [
    # Common
    "ResponseBase",
    "ErrorResponse",
    "PaginatedResponse",
    # Auth
    "LoginRequest",
    "TokenResponse",
    "RefreshTokenRequest",
    "ChangePasswordRequest",
    "UserResponse",
    # User Management
    "UserRoleEnum",
    "UserBase",
    "UserCreate",
    "UserUpdate",
    "UserStatusUpdate",
    "ResetPasswordRequest",
    "UserDetailResponse",
    "UserListResponse",
    # Zone Management
    "ZoneBase",
    "ZoneCreate",
    "ZoneUpdate",
    "ZoneResponse",
    "ZoneSimpleResponse",
    "ZoneListResponse",
    "ZoneTreeNode",
    "ZoneTreeResponse",
    # Camera Management
    "CameraStatusEnum",
    "CameraBase",
    "CameraCreate",
    "CameraUpdate",
    "CameraToggleRequest",
    "CameraResponse",
    "CameraSimpleResponse",
    "CameraListResponse",
    "CameraStatusResponse",
    "CameraStatusListResponse",
    "CameraTestResult",
    # Group Management
    "GroupBase",
    "GroupCreate",
    "GroupUpdate",
    "GroupResponse",
    "GroupSimpleResponse",
    "GroupListResponse",
    "GroupStatsResponse",
    # Person Management
    "PersonBase",
    "PersonCreate",
    "PersonUpdate",
    "PersonStatusUpdate",
    "PersonResponse",
    "PersonDetailResponse",
    "PersonSimpleResponse",
    "PersonListResponse",
    "FaceImageResponse",
    "FaceUploadResponse",
    "PersonImportRequest",
    "PersonImportResult",
    # Alert Management
    "AlertTypeEnum",
    "AlertStatusEnum",
    "AlertResponse",
    "AlertListResponse",
    "AlertProcessRequest",
    "AlertIgnoreRequest",
    "AlertBatchProcessRequest",
    "AlertBatchProcessResult",
    "AlertStatistics",
    "AlertTrendItem",
    "AlertTrendResponse",
    "AlertCreateRequest",
    # Settings Management
    "ConfigValueType",
    "ConfigItemResponse",
    "ConfigGroupResponse",
    "SystemConfigResponse",
    "ConfigUpdateItem",
    "ConfigUpdateRequest",
    "ConfigUpdateResult",
    "CleanupTypeEnum",
    "CleanupRequest",
    "CleanupResult",
    "CleanupLogResponse",
    "CleanupLogListResponse",
    "DiskUsage",
    "ServiceStatus",
    "DatabaseStatus",
    "SystemStatusResponse",
    # Operation Log Management
    "ActionTypeEnum",
    "TargetTypeEnum",
    "OperationLogResponse",
    "OperationLogListResponse",
    "OperationLogCreateRequest",
    "OperationLogStatistics",
    "ACTION_LABELS",
    "TARGET_TYPE_LABELS",
]
